### ISSUE TITLE
typings when consuming from typescript

### ISSUE THREAD

**Issue by wkrueger** [JoshYaxley/Wipefest.Core#1]
Hi there I just found out you had an API and was curious if I could use it to quickly generate some summaries.

I use typescript too, 1st thing I noticed is that the typings do not match the examples in the main file. Might be something in the build process. I might have a look at it.

Steps:

 - Empty project
 - Simple tsconfig.json ex:  `{ "compilerOptions" : { "strict": true, "target": "es2017" }}`
 - `yarn add @wipefest/core`
 - Create `index.ts`, write `import { WarcraftLogsReportService } from '@wipefest/core'`
 - Invoking `tsc` will yell WarcraftLogsReportService  doesnt exist.

**Comment by JoshYaxley** [comment]
Interesting. It's been a while since I tried using it in TypeScript (I wrote the CLI in JavaScript: https://github.com/JoshYaxley/Wipefest.Cli/blob/master/handlers/get-report.js).

It definitely used to work in TypeScript though - hence the example in the readme!

If you can dig out the reason at all that would be really helpful :)

**Comment by JoshYaxley** [comment]
It looks like I can fix the problem by changing all my imports/exports to relative paths:

`import { HttpService } from 'infrastructure/http.service';`

to

`import { HttpService } from '../infrastructure/http.service';`

and

`export * from 'warcraft-logs/warcraft-logs-report.service';`

to

`export * from './warcraft-logs/warcraft-logs-report.service';`

etc.

I'll go through the library tomorrow to make the necessary changes and push up a new version (probably 0.2.9).

**Comment by JoshYaxley** [comment]
Wasn't too hard to change in the end, so I went ahead and fixed it: 069c3af

Update to 0.2.9 and let me know if it's fixed!

**Comment by wkrueger** [comment]
Yeah I was looking into some sort of adding a transformation to the generated typings without the need to rewrite the import mappings, but it seemed no trivial task. So I guess we're stuck on relative paths if the module is to be consumed as a library...

Seems to be working great so far, thanks!

**Comment by JoshYaxley** [comment]
Yeah I would've preferred to stay away from having relative paths so that `import` statements could be copied from place to place and files could be moved around but ah well - at least it works!
